#spring:
  #data:
    #mongodb:
      #host: localhost
      #port: 27017
      #database: ProfileDB
      #repositories:
        #enabled: true  
        
server:
  port: 1996        
        
        
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/loandb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect        

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${random.value}
